package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/tc3oliver/version-aware-code-mcp/config"
	"github.com/tc3oliver/version-aware-code-mcp/managed"
	"github.com/tc3oliver/version-aware-code-mcp/store"
	"github.com/tc3oliver/version-aware-code-mcp/vacctx"
)

// Managed mode is the query plane running on the contexts the management plane
// built, instead of on a configuration file someone wrote by hand.
//
// It is not a second query plane. Everything here produces one *[config.Config]
// and hands it to the same addTools static mode uses, so the resolver, the
// tools and the adapters cannot tell the two modes apart: decision-4's split is
// about where a configuration comes from, not about what serves it.
//
// Nothing here clones, fetches or reaches a forge. It reads records and clone
// paths that `vacmcp repo` and `vacmcp context` already wrote, which is what
// keeps `serve` local-only in either mode.

const (
	// generatedConfig is the file the configuration built below is written to,
	// under the data directory's runtime/. It is there to be read by an operator
	// asking what this server is actually serving; it is not a source of truth,
	// and deleting it loses nothing.
	generatedConfig = "generated-config.yaml"

	// defaultZoektURL is where a zoekt-webserver listens unless told otherwise,
	// the endpoint config/example.yaml documents.
	//
	// The search endpoint and the graph command are flags rather than records in
	// the data directory because they are properties of how this machine runs
	// Zoekt and CBM, not of any repository or context. Indexing a context needs
	// neither of them: it runs zoekt-git-index and `codebase-memory-mcp cli`,
	// both one-shot, so a data directory can be built with no server running at
	// all and then be served by whichever one this deployment has.
	defaultZoektURL = "http://127.0.0.1:6070"
)

// readyContexts returns the records the query plane may serve, ordered by ID.
// READY is the only state a context is served in, so every other one is left
// out here rather than filtered somewhere further down.
func readyContexts(s *store.Store) ([]store.Context, error) {
	contexts, err := s.Contexts()
	if err != nil {
		return nil, err
	}
	ready := make([]store.Context, 0, len(contexts))
	for _, c := range contexts {
		if c.State == managed.ContextReady {
			ready = append(ready, c)
		}
	}
	return ready, nil
}

// managedConfig builds the configuration for the READY contexts of s, writes it
// to the data directory's generated file and returns it as config.Load parses
// it back.
//
// Loading it back rather than serving the value built here is deliberate: the
// file an operator reads and the configuration this process runs on are then
// provably the same thing, checked by the same strict parser a hand-written
// configuration goes through. Both `serve --managed` and `doctor --managed`
// come through here, so the file is rewritten on each of them.
func managedConfig(s *store.Store, zoektURL, cbmCommand string) (*config.Config, error) {
	contexts, err := readyContexts(s)
	if err != nil {
		return nil, err
	}

	cfg := config.Config{
		Providers:    config.Providers{Zoekt: config.Zoekt{URL: zoektURL}, CBM: config.CBM{Command: cbmCommand}},
		Repositories: map[string]config.Repository{},
		Contexts:     map[string]vacctx.Workspace{},
	}
	for _, c := range contexts {
		members := make([]vacctx.CodeContext, 0, len(c.Members))
		for _, member := range c.Members {
			path, err := s.RepositoryDir(member.Repository)
			if err != nil {
				return nil, err
			}
			// The local clone and nothing else. The repository record also
			// carries the remote URL it was cloned from, and that must not
			// travel into a runtime configuration: the query plane never reaches
			// a remote, so a URL there would be a credential-adjacent field
			// written into a file for no reader at all.
			cfg.Repositories[member.Repository] = config.Repository{Path: path}
			members = append(members, vacctx.CodeContext{
				ID:         c.ID,
				Repository: member.Repository,
				Branch:     member.Branch,
				Revision:   member.Revision,
				GraphRef:   member.GraphRef,
			})
		}
		cfg.Contexts[c.ID] = vacctx.Workspace{ID: c.ID, Members: members}
	}

	// Rendered by config itself, rather than by printing the fields here, is
	// what keeps the generated file from drifting away from the shape
	// config.Load parses — including which of the two spellings a context is
	// written in, which is the record's own shape all over again and is decided
	// in one place for both.
	body, err := config.Marshal(&cfg)
	if err != nil {
		return nil, fmt.Errorf("serve: cannot generate the configuration of %s: %w", s.Root(), err)
	}
	const header = "# Generated by vacmcp from the records in this data directory, and rewritten\n" +
		"# every time a managed server starts. Change the contexts, not this file.\n"
	path := filepath.Join(s.RuntimeDir(), generatedConfig)
	if err := os.WriteFile(path, append([]byte(header), body...), 0o600); err != nil {
		return nil, fmt.Errorf("serve: cannot write %s: %w", path, err)
	}

	// A data directory with nothing READY serves no contexts, which is exactly
	// the server `serve` without a --config gives: every id answered with
	// CONTEXT_NOT_FOUND. config.Load refuses a file declaring no context, so it
	// is not asked about one.
	if len(cfg.Contexts) == 0 {
		return &cfg, nil
	}
	return config.Load(path)
}
