#!/usr/bin/env bash
# Makes the versioned demo repository queryable: one branch-aware Zoekt index,
# one CBM graph per release, and the configuration naming both.
#
#   testdata/fixture/zoekt-index   main + release/v1 + release/v2 in one index
#   testdata/fixture/worktrees/    a checkout per release, what CBM indexes
#   testdata/fixture/config.yaml   repositories + contexts for the integration tests
#
# Each release gets its own CBM project, named after its graph_ref. Sharing one
# project across versions would trace calls against the other version's graph,
# which is the cross-version contamination this server exists to prevent.
#
# Everything here is a build artifact: the whole fixture directory is wiped and
# rebuilt on every run, so repeated runs and CI runs land on the same indexes.
# config.yaml is written last, so its presence means the run got all the way
# through — that is what internal/demorepo.Prepared checks.
set -euo pipefail

root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
repo="$root/testdata/versioned-demo-repo"
fixture="$root/testdata/fixture"

# codebase-memory-mcp is not installed system-wide everywhere; CI points CBM_BIN
# at whatever it downloaded.
cbm=${CBM_BIN:-codebase-memory-mcp}

for tool in git zoekt-git-index "$cbm"; do
	if ! command -v "$tool" >/dev/null 2>&1; then
		echo "prepare-fixture: $tool not found; see CONTRIBUTING.md" >&2
		exit 1
	fi
done

rm -rf "$fixture"
"$root/testdata/gen-versioned-demo-repo.sh"

# Zoekt indexes several branches of one git repository into one shard, so the
# repo is read once and a query picks its version with branch:.
zoekt-git-index -index "$fixture/zoekt-index" \
	-branches "main,release/v1,release/v2" "$repo"

# CBM indexes a directory, not a revision, so each release needs a real checkout.
graph() {
	local branch=$1 graph_ref=$2
	local tree="$fixture/worktrees/$graph_ref"
	git -C "$repo" worktree add --detach -q "$tree" "refs/heads/$branch"
	"$cbm" cli index_repository --repo-path "$tree" --name "$graph_ref"
}

graph release/v1 vacmcp-demo-v1
graph release/v2 vacmcp-demo-v2

# One more graph, and not a version of the demo repository: two packages
# declaring one function name, which is the ambiguity trace_calls has to report
# both candidates for rather than answer from whichever CBM listed first. The
# demo repository duplicates no name, so it is built here — once, with the rest
# of the baseline — instead of by each test that asks about it.
ambiguous="$fixture/ambiguous"
mkdir -p "$ambiguous/alpha" "$ambiguous/beta" "$ambiguous/only"
printf 'module ambiguous\n\ngo 1.26\n' >"$ambiguous/go.mod"
printf 'package alpha\n\nfunc Duplicated() {}\n' >"$ambiguous/alpha/dup.go"
printf 'package beta\n\nfunc Duplicated() {}\n' >"$ambiguous/beta/dup.go"
printf 'package only\n\nfunc Unique() {}\n' >"$ambiguous/only/once.go"
"$cbm" cli index_repository --repo-path "$ambiguous" --name vacmcp-demo-ambiguous

# The revisions are resolved here rather than written down: regenerating the
# fixture may move them, and a config naming a stale revision is exactly the
# SOURCE_MISMATCH the server is supposed to catch.
cat >"$fixture/config.yaml" <<EOF
# Generated by testdata/prepare-fixture.sh. Re-run the script instead of editing.
#
# The repository key is the name Zoekt derived from the indexed directory, so a
# repo: filter built from this configuration matches the index.

providers:
  zoekt:
    url: http://127.0.0.1:6070
  cbm:
    command: $cbm

repositories:
  versioned-demo-repo:
    path: $repo

contexts:
  demo-v1:
    repository: versioned-demo-repo
    branch: release/v1
    revision: $(git -C "$repo" rev-parse refs/heads/release/v1)
    graph_ref: vacmcp-demo-v1
  demo-v2:
    repository: versioned-demo-repo
    branch: release/v2
    revision: $(git -C "$repo" rev-parse refs/heads/release/v2)
    graph_ref: vacmcp-demo-v2
EOF

echo "prepare-fixture: ready at $fixture"
