#!/usr/bin/env bash
# Makes the versioned demo repository queryable: one branch-aware Zoekt index,
# one CBM graph per release, and the configuration naming both.
#
#   testdata/fixture/zoekt-index   both repositories, every branch, one index
#   testdata/fixture/worktrees/    a checkout per graph, what CBM indexes
#   testdata/fixture/cbm-data/     the graphs below, CBM's own store
#   testdata/fixture/config.yaml   repositories + contexts for the integration tests
#
# Each release gets its own CBM project, named after its graph_ref. Sharing one
# project across versions would trace calls against the other version's graph,
# which is the cross-version contamination this server exists to prevent.
#
# A second repository stands beside the first: same Zoekt index directory,
# indexed separately so Zoekt derives a repository name of its own from its
# directory (decision-11 §1), colliding with the first on purpose — same path,
# same symbol name, different content — so multi-repository search, read and
# trace can be proven against a real collision. See
# testdata/gen-second-demo-repo.sh.
#
# Everything here is a build artifact: the whole fixture directory is wiped and
# rebuilt on every run, so repeated runs and CI runs land on the same indexes.
# config.yaml is written last, so its presence means the run got all the way
# through — that is what internal/demorepo.Prepared checks.
set -euo pipefail

root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
repo="$root/testdata/versioned-demo-repo"
repo2="$root/testdata/second-demo-repo"
fixture="$root/testdata/fixture"

# codebase-memory-mcp is not installed system-wide everywhere; CI points CBM_BIN
# at whatever it downloaded.
cbm=${CBM_BIN:-codebase-memory-mcp}

# CBM has no --data-dir flag; it derives its store from this variable, falling
# back to ~/.cache/codebase-memory-mcp. Every index_repository call below is
# kept out of that global, developer-shared directory — otherwise a long
# enough run of `make test-integration` accumulates CBM projects there
# forever, which is what degraded the real-engine suite before this existed.
# A caller (CI) that already exported this to start a shared daemon keeps its
# value; a bare local run defaults to the fixture's own subdirectory, wiped
# with the rest of it below.
export CBM_CACHE_DIR="${CBM_CACHE_DIR:-$fixture/cbm-data}"

for tool in git zoekt-git-index "$cbm"; do
	if ! command -v "$tool" >/dev/null 2>&1; then
		echo "prepare-fixture: $tool not found; see CONTRIBUTING.md" >&2
		exit 1
	fi
done

rm -rf "$fixture"
"$root/testdata/gen-versioned-demo-repo.sh"
"$root/testdata/gen-second-demo-repo.sh"

# Zoekt indexes several branches of one git repository into one shard, so each
# repo is read once and a query picks its version with branch:. Two directories
# indexed into the same -index directory is all it takes for Zoekt to serve two
# repository names out of it (decision-11 §1) — no other mechanism is needed.
zoekt-git-index -index "$fixture/zoekt-index" \
	-branches "main,release/v1,release/v2" "$repo"
zoekt-git-index -index "$fixture/zoekt-index" \
	-branches "main" "$repo2"

# CBM indexes a directory, not a revision, so each release needs a real
# checkout. repo_path is a parameter, not just repo, because the second
# repository's graph is built the same way as the first's.
graph() {
	local repo_path=$1 branch=$2 graph_ref=$3
	local tree="$fixture/worktrees/$graph_ref"
	git -C "$repo_path" worktree add --detach -q "$tree" "refs/heads/$branch"
	"$cbm" cli index_repository --repo-path "$tree" --name "$graph_ref"
}

graph "$repo" release/v1 vacmcp-demo-v1
graph "$repo" release/v2 vacmcp-demo-v2
graph "$repo2" main vacmcp-demo2

# One more graph, and not a version of the demo repository: two packages
# declaring one function name, which is the ambiguity trace_calls has to report
# both candidates for rather than answer from whichever CBM listed first. The
# demo repository duplicates no name, so it is built here — once, with the rest
# of the baseline — instead of by each test that asks about it.
ambiguous="$fixture/ambiguous"
mkdir -p "$ambiguous/alpha" "$ambiguous/beta" "$ambiguous/only"
printf 'module ambiguous\n\ngo 1.26\n' >"$ambiguous/go.mod"
printf 'package alpha\n\nfunc Duplicated() {}\n' >"$ambiguous/alpha/dup.go"
printf 'package beta\n\nfunc Duplicated() {}\n' >"$ambiguous/beta/dup.go"
printf 'package only\n\nfunc Unique() {}\n' >"$ambiguous/only/once.go"
"$cbm" cli index_repository --repo-path "$ambiguous" --name vacmcp-demo-ambiguous

# The revisions are resolved here rather than written down: regenerating the
# fixture may move them, and a config naming a stale revision is exactly the
# SOURCE_MISMATCH the server is supposed to catch.
cat >"$fixture/config.yaml" <<EOF
# Generated by testdata/prepare-fixture.sh. Re-run the script instead of editing.
#
# The repository key is the name Zoekt derived from the indexed directory, so a
# repo: filter built from this configuration matches the index.

providers:
  zoekt:
    url: http://127.0.0.1:6070
  cbm:
    command: $cbm

repositories:
  versioned-demo-repo:
    path: $repo
  second-demo-repo:
    path: $repo2

contexts:
  demo-v1:
    repository: versioned-demo-repo
    branch: release/v1
    revision: $(git -C "$repo" rev-parse refs/heads/release/v1)
    graph_ref: vacmcp-demo-v1
  demo-v2:
    repository: versioned-demo-repo
    branch: release/v2
    revision: $(git -C "$repo" rev-parse refs/heads/release/v2)
    graph_ref: vacmcp-demo-v2
  # A multi-member context, on top of the two single-repository ones above:
  # versioned-demo-repo's release/v1 (reusing demo-v1's own graph_ref, since it
  # is the same repository at the same revision) paired with second-demo-repo.
  # Both declare a handler.go with a LegacyHandler of their own, which is the
  # collision cross-repository search, read and trace are proven against.
  demo-multi:
    members:
      - repository: versioned-demo-repo
        branch: release/v1
        revision: $(git -C "$repo" rev-parse refs/heads/release/v1)
        graph_ref: vacmcp-demo-v1
      - repository: second-demo-repo
        branch: main
        revision: $(git -C "$repo2" rev-parse refs/heads/main)
        graph_ref: vacmcp-demo2
EOF

echo "prepare-fixture: ready at $fixture"
